Tactsoft/Controllers/Admin/BoardController.cs
using Microsoft.AspNetCore.Mvc;
using Tactsoft.Core.Entities;
using Tactsoft.Service.Services;

namespace Tactsoft.Controllers.Admin
{
    public class BoardController : Controller
    {
        private readonly IBoardService _boardService;
        public BoardController(IBoardService boardService)
        {
            _boardService = boardService;
        }

        public async Task<IActionResult> Index()
        {
            var Result = await _boardService.GetAllAsync();
            return View(Result);
        }


        public async Task<IActionResult> Details(int id)
        {
            var Result = await _boardService.FindAsync(id);
            return View(Result);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Board board)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _boardService.InsertAsync(board);
                    TempData["successAlert"] = "Country Save Successfull.";
                    return RedirectToAction(actionName: nameof(Index));
                }
                return View(board);

            }
            catch
            {
                return View("Create", board);
            }
        }


        public async Task<ActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var Result = await _boardService.FindAsync(id);
            return View(Result);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Board board)
        {
            try
            {
                var Result = await _boardService.FindAsync(board.Id);
                if (Result != null)
                {
              
                    await _boardService.UpdateAsync(Result);
                    TempData["successAlert"] = "Country Update Successfull.";
                    return RedirectToAction(actionName: nameof(Index));

                }
                else
                {
                    return NotFound();
                }
            }
            catch
            {
                return View(board);
            }
        }


        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var Result = await _boardService.FindAsync(id);
            return View(Result);
        }


        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Deletecon(int id)
        {
            try
            {
                var Result = await _boardService.FindAsync(id);
                if (Result == null)
                {
                    return NotFound();
                }
                await _boardService.DeleteAsync(Result);
                TempData["successAlert"] = "Country Delete Successfull.";
                return RedirectToAction(actionName: nameof(Index));
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }
    }
}

Tactsoft/Controllers/Admin/CountryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics.Metrics;
using Tactsoft.Core.Entities;
using Tactsoft.Service.Services;

namespace Tactsoft.Controllers.Admin
{
    public class CountryController : Controller
    {
        private readonly ICountryService _countryService;
        public CountryController(ICountryService countryService)
        {
            this._countryService = countryService;
        }
        
        public async Task< IActionResult> Index()
        {
            var Result=await _countryService.GetAllAsync();
            return View(Result);
        }

       
        public async Task<IActionResult> Details(int id)
        {
            var Result=await _countryService.FindAsync(id);
            return View(Result);
        }

       
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> Create(Country country)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _countryService.InsertAsync(country);
                    TempData["successAlert"] = "Country Save Successfull.";
                    return RedirectToAction(actionName: nameof(Index));
                }
                return View(country);
               
            }
            catch
            {
                return View("Create",country);
            }
        }

        
        public async  Task< ActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var Result = await _countryService.FindAsync(id);
            return View(Result);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> Edit(Country country)
        {
            try
            {
                var Result = await _countryService.FindAsync(country.Id);
                if (Result != null)
                {
                    Result.CountryName = country.CountryName;
                    await _countryService.UpdateAsync(Result);
                    TempData["successAlert"] = "Country Update Successfull.";
                    return RedirectToAction(actionName: nameof(Index));

                }
                else
                {
                    return NotFound();
                }
            }
            catch
            {
                return View(country);
            }
        }

        
        public async Task< IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var Result = await _countryService.FindAsync(id);
            return View(Result);
        }

        
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Deletecon(int id)
        {
            try
            {
                var Result = await _countryService.FindAsync(id);
                if (Result == null)
                {
                    return NotFound();
                }
                await _countryService.DeleteAsync(Result);
                TempData["successAlert"] = "Country Delete Successfull.";
                return RedirectToAction(actionName: nameof(Index));
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }
    }
}

Tactsoft/Controllers/Admin/ResultController.cs
using Microsoft.AspNetCore.Mvc;
using Tactsoft.Core.Entities;
using Tactsoft.Service.Services;

namespace Tactsoft.Controllers.Admin
{
    public class ResultController : Controller
    {
        private readonly IResultService   _resultService;
        public ResultController(IResultService resultService)
        {
            _resultService = resultService;
        }

        public async Task<IActionResult> Index()
        {
            var Result = await _resultService.GetAllAsync();
            return View(Result);
        }


        public async Task<IActionResult> Details(int id)
        {
            var Result = await _resultService.FindAsync(id);
            return View(Result);
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Result result)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _resultService.InsertAsync(result);
                    TempData["successAlert"] = "Country Save Successfull.";
                    return RedirectToAction(actionName: nameof(Index));
                }
                return View(result);

            }
            catch
            {
                return View("Create", result);
            }
        }


        public async Task<ActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var Result = await _resultService.FindAsync(id);
            return View(Result);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Result result)
        {
            try
            {
                var Result = await _resultService.FindAsync(result.Id);
                if (Result != null)
                {

                    await _resultService.UpdateAsync(Result);
                    TempData["successAlert"] = "Country Update Successfull.";
                    return RedirectToAction(actionName: nameof(Index));

                }
                else
                {
                    return NotFound();
                }
            }
            catch
            {
                return View(result);
            }
        }


        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var Result = await _resultService.FindAsync(id);
            return View(Result);
        }


        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Deletecon(int id)
        {
            try
            {
                var Result = await _resultService.FindAsync(id);
                if (Result == null)
                {
                    return NotFound();
                }
                await _resultService.DeleteAsync(Result);
                TempData["successAlert"] = "Country Delete Successfull.";
                return RedirectToAction(actionName: nameof(Index));
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }
    }
}

Tactsoft/Controllers/Admin/ThanaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Tactsoft.Core.Entities;
using Tactsoft.Service.Services;

namespace Tactsoft.Controllers.Admin
{
    public class ThanaController : Controller
    {
        private readonly IThanaService _thanaService;
        private readonly IDistrictService _DistrictService;
        public ThanaController(IThanaService thanaService, IDistrictService districtService)
        {
            _thanaService = thanaService;
            _DistrictService = districtService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var Result = await _thanaService.GetAllAsync(x => x.District);
            return View(Result);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["DistrictId"] = _DistrictService.Dropdown();
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(Thana thana)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _thanaService.InsertAsync(thana);
                    TempData["successAlert"] = "Thana Save Successfull.";
                    return RedirectToAction(actionName: nameof(Index));
                }
                ViewData["DistrictId"] = _DistrictService.Dropdown();
                return View(thana);

            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                if (id == 0)
                {
                    return NotFound();
                }
                ViewData["DistrictId"] = _DistrictService.Dropdown();
                var Result = await _thanaService.FindAsync(id);
                return View(Result);

            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Thana thana)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var Result = await _thanaService.FindAsync(thana.Id);
                    if (Result != null)
                    {
                        Result.DistrictId = thana.DistrictId;
                        Result.ThanaName = thana.ThanaName;
                        await _thanaService.UpdateAsync(Result);
                        TempData["successAlert"] = "Thana Update Successfull.";
                        return RedirectToAction(actionName: nameof(Index));

                    }
                    else
                    {
                        return NotFound();
                    }
                }
                ViewData["DistrictId"] = _DistrictService.Dropdown();
                return View(thana);

            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                if (id == 0)
                {
                    return NotFound();
                }
                var Result = await _thanaService.FindAsync(x => x.Id == id, x => x.District);
                return View(Result);

            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                if (id == 0)
                {
                    return NotFound();
                }
                var Result = await _thanaService.FindAsync(x => x.Id == id, x => x.District);
                return View(Result);

            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteCon(int id)
        {
            try
            {

                var Result = await _thanaService.FindAsync(id);
                if (Result == null)
                {
                    return NotFound();
                }
                await _thanaService.DeleteAsync(Result);
                TempData["successAlert"] = "Thana Delete Successfull.";
                return RedirectToAction(actionName: nameof(Index));


            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }

        }
    }
}

Tactsoft/Views/Shared/Partial/Footer.cshtml
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.2.0
    </div>
</footer>

Tactsoft/Views/Shared/Partial/Navbar.cshtml
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/admin-lte/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/admin-lte/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="~/admin-lte/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>


        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-user"></i>
            </a>

            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header"></span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-people-roof mr-2"></i> Profile
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports

                </a>
                <div class="dropdown-divider"></div>
                <form method="post" asp-controller="account" asp-action="logout">
                    <button type="submit" style="width:auto"
                            class="nav-link btn btn-link py-0">
                        Logout
                    </button>
                </form>
            </div>


        </li>
    </ul>
</nav>
<!-- /.navbar -->

Tactsoft/Views/Shared/Partial/Sidebar.cshtml
<aside class="main-sidebar sidebar-light-primary elevation-1">
    
    <a href="index3.html" class="brand-link">
        <img src="~/photo.jpg" alt="Tactsoft Logo" class="brand-image img-circle elevation-1" style="opacity: .8">
        <span class="brand-text font-weight-light">Tactsoft</span>
    </a>

    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fas fa-globe nav-icon"></i>
                        <p>
                            All Tables
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Country" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p>Country</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="District" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p>District</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Thana" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p>Thana</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Relative" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p>Relative</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Reading" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p>Reading</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Speaking" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p>Speaking</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Writing" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p>Writing</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="CompanySize" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p>CompanySize</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="IndustryType" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p>Industry Type</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="JobCategory" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p>Job Category</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="ResumeReceivingOption" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p> Resume Receiving Option</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="ServiceType" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p> Service Type</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="OrganizationType" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p> Organization Type</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="BloodGroup" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p> Blood Group</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Board" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p> Board</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="YearOfPassing" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p> Year</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Result" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p> Result</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="DegreeTitle" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p> Degree</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Expertise" asp-action="Index">
                                <i class="fas fa-map-marked-alt nav-icon"></i>
                                <p> Expertise</p>
                            </a>
                        </li>
                    </ul>


                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fas fa-globe nav-icon"></i>
                        <p>
                            All Tables
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Company" asp-action="Index">
                                <i class="fas fa-user-tie nav-icon"></i>
                                <p>Company</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="PostingJobs" asp-action="Index">
                                <i class="fas fa-user-tie nav-icon"></i>
                                <p>Posting Jobs</p>
                            </a>
                        </li>
                    </ul>

                </li>
                
            </ul>
        </nav>
    </div>
</aside>