Tactsoft/Controllers/Admin/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace Tactsoft.Controllers.Admin
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Tactsoft/Controllers/Admin/PersonalDetailsController.cs
using Microsoft.AspNetCore.Mvc;
using Tactsoft.Core.Entities;
using Tactsoft.Service.Services;

namespace Tactsoft.Controllers.Admin
{
    public class PersonalDetailsController : Controller
    {
        private readonly IPersonalDetailsService _personalDetailsService;
        private readonly IBloodGroupService _bloodGroupService;

		private readonly IJobseekerService _jobseekerService;
		public PersonalDetailsController(IPersonalDetailsService personalDetailsService, IJobseekerService jobseekerService, IBloodGroupService bloodGroupService)
        {
            _personalDetailsService = personalDetailsService;
            _bloodGroupService = bloodGroupService;
            _jobseekerService = jobseekerService;

		}

        public async Task<IActionResult> Index()
        {
            var Result = await _personalDetailsService.GetAllAsync(x=>x.BloodGroup);
			TempData["jobseekerId"] = _jobseekerService.GetIdByUeseName(User.Identity.Name);
			ViewData["jobseekerId"] = _jobseekerService.GetIdByUeseName(User.Identity.Name);


			return View(Result);
        }

        [HttpGet]
        public async Task<IActionResult> AddorEdit(int id = 0)
        {
			ViewData["BloodGroupId"] = _bloodGroupService.Dropdown();
			if (id == 0)
            {
                return View(new PersonalDetails());
            }
            else
            {
                var personalDetails = await _personalDetailsService.FindAsync(x => x.JobseekerId == id);


                if (personalDetails == null)
                {
                    return NotFound();
                }
                return View(personalDetails);
            }
        }


		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> AddorEdit(long id, PersonalDetails personalDetails)
        {

          
            //Save Data
            if (id == 0)
			{
                
                await _personalDetailsService.InsertAsync(personalDetails);
				return RedirectToAction("Index", "JobSeekerDashboard");
			}
			else
			{
                var loggedInUserName = HttpContext.Session.GetString("UserName");
                var jobSeekerId = _jobseekerService.GetJobseekerByUserName(loggedInUserName).Id;
                personalDetails.JobseekerId = jobSeekerId;

                await _personalDetailsService.UpdateAsync(personalDetails);
				return RedirectToAction("Index", "JobSeekerDashboard");

			}
			return View(new PersonalDetails());
		}









		public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }
            var Result = await _personalDetailsService.FindAsync(id);
            return View(Result);
        }


        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Deletecon(int id)
        {
            try
            {
                var Result = await _personalDetailsService.FindAsync(id);
                if (Result == null)
                {
                    return NotFound();
                }
                await _personalDetailsService.DeleteAsync(Result);
                TempData["successAlert"] = "Personal Details Delete Successfull.";
                return RedirectToAction(actionName: nameof(Index));
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }



		public async Task<IActionResult> Details(long id)

		{

            var deatisl= await _personalDetailsService.FindAsync(x => x.JobseekerId == id);

			var val = await _personalDetailsService.FindAsync(m => m.Id == deatisl.Id, i => i.BloodGroup);
			return View(val);


		}
	}
}

Tactsoft/Views/PersonalDetails/AddorEdit.cshtml
@model Tactsoft.Core.Entities.PersonalDetails
@*
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}*@



<form asp-action="AddorEdit" asp-controller="PersonalDetails"  enctype="multipart/form-data">

	<div asp-validation-summary="ModelOnly" class="text-danger"></div>

	<input asp-for="@Model.Id" type="hidden"  />
	
	<input asp-for="JobseekerId" type="hidden" value="@(TempData["jobseekerId"])" />
	<div class="row mt-2 ">
		<div class="col-md-6">
			<div class="row mb-2">
				<label asp-for="FirstName" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="FirstName" class="form-control" />
					<span asp-validation-for="FirstName" class="text-danger"></span>
				</div>
			</div>
			<div class="row mb-2">
				<label asp-for="LastName" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="LastName" class="form-control" />
					<span asp-validation-for="LastName" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="LastName" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="LastName" class="form-control" />
					<span asp-validation-for="LastName" class="text-danger"></span>
				</div>
			</div>
			<div class="row mb-2">
				<label asp-for="FatherName" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="FatherName" class="form-control" />
					<span asp-validation-for="FatherName" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="MotherName" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="MotherName" class="form-control" />
					<span asp-validation-for="MotherName" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="DateofBirth" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input type="date" asp-for="DateofBirth" class="form-control" min="@(DateTime.Now.ToString("yyyy-MM-dd"))" />
					<span asp-validation-for="DateofBirth" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="Gender" class="col-md-4 col-form-label"></label>
				<div class="col-md-8 pt-2">
					<label class="radio-inline mx-2">
						@Html.RadioButtonFor(model => model.Gender, "Male", htmlAttributes: new { @class = "form-check-input" }) Male
					</label>
					<label class="radio-inline mx-2">
						@Html.RadioButtonFor(model => model.Gender, "Female", htmlAttributes: new { @class = "form-check-input" }) Female
					</label>
					<label class="radio-inline mx-2">
						@Html.RadioButtonFor(model => model.Gender, "Other", htmlAttributes: new { @class = "form-check-input" }) Other
					</label>
					<br />
					<span asp-validation-for="Gender" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label class="col-md-4 col-form-label">Religion</label>
				<div class="col-md-8">
					<input rows="4" asp-for="Religion" class="form-control" />
					<span asp-validation-for="Religion" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="MaritalStatus" class="col-md-4 col-form-label"></label>
				<div class="col-md-8 pt-2">
					<label class="radio-inline mx-2">
						@Html.RadioButtonFor(model => model.MaritalStatus, "Married", htmlAttributes: new { @class = "form-check-input" }) Married
					</label>
					<label class="radio-inline mx-2">
						@Html.RadioButtonFor(model => model.MaritalStatus, "Unmarried", htmlAttributes: new { @class = "form-check-input" }) Unmarried
					</label>

					<br />
					<span asp-validation-for="Gender" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="Nationality" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="Nationality" class="form-control" />
					<span asp-validation-for="Nationality" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label class="col-md-4 col-form-label">National Id</label>
				<div class="col-md-8">
					<input asp-for="NationalId" class="form-control" />
					<span asp-validation-for="NationalId" class="text-danger"></span>
				</div>
			</div>

		</div>


		<div class="col-md-6">


			<div class="row mb-2">
				<label asp-for="PassportNumber" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="PassportNumber" class="form-control" />
					<span asp-validation-for="PassportNumber" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="PassportIssueDate" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input type="date" asp-for="PassportIssueDate" class="form-control" min="@(DateTime.Now.ToString("yyyy-MM-dd"))" />
					<span asp-validation-for="PassportIssueDate" class="text-danger"></span>
				</div>
			</div>


			<div class="row mb-2">
				<label asp-for="PrimaryMobile" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="PrimaryMobile" class="form-control" />
					<span asp-validation-for="PrimaryMobile" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="SecondaryMobile" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="SecondaryMobile" class="form-control" />
					<span asp-validation-for="SecondaryMobile" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="EmergencContact" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="EmergencContact" class="form-control" />
					<span asp-validation-for="EmergencContact" class="text-danger"></span>
				</div>
			</div>
			<div class="row mb-2">
				<label asp-for="PrimaryEmail" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="PrimaryEmail" class="form-control" />
					<span asp-validation-for="PrimaryEmail" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="AlternateEmail" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="AlternateEmail" class="form-control" />
					<span asp-validation-for="AlternateEmail" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="BloodGroupId" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<select asp-for="BloodGroupId" class="form-control" asp-items="ViewBag.BloodGroupId">
						<option value="">--Select Blood Group--</option>
					</select>
					<span asp-validation-for="BloodGroupId" class="text-danger"></span>
				</div>
			</div>
			<div class="row mb-2">
				<label asp-for="Height" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="Height" class="form-control" />
					<span asp-validation-for="Height" class="text-danger"></span>
				</div>
			</div>

			<div class="row mb-2">
				<label asp-for="Weight" class="col-md-4 col-form-label"></label>
				<div class="col-md-8">
					<input asp-for="Weight" class="form-control" />
					<span asp-validation-for="Weight" class="text-danger"></span>
				</div>
			</div>


			<div class="col-12">
				<button type="submit" value="Create" class="btn btn-primary">Submit</button>
			</div>

		</div>


	</div>


</form>





<script src="~/admin-lte/js/imagepreview.js"></script>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");

	}
    }

Tactsoft/Views/PersonalDetails/Details.cshtml
@model Tactsoft.Core.Entities.PersonalDetails

<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">

                  
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                      
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <dl class="row">
                                <dt class="col-md-3">
                                    @Html.DisplayNameFor(model => model.FirstName)
                                </dt>
                                <dd class="col-md-9">
                                    @Html.DisplayFor(model => model.FirstName)
                                </dd>
                                <dt class="col-md-3">
                                    @Html.DisplayNameFor(model => model.LastName)
                                </dt>
                                <dd class="col-md-9">
                                    @Html.DisplayFor(model => model.LastName)
                                </dd>

                                <dt class="col-md-3">
                                    @Html.DisplayNameFor(model => model.NationalId)
                                </dt>
                                <dd class="col-md-9">
                                    @Html.DisplayFor(model => model.NationalId)
                                </dd>

                                <dt class="col-md-3">
                                    @Html.DisplayNameFor(model => model.Religion)
                                </dt>
                                <dd class="col-md-9">
                                    @Html.DisplayFor(model => model.Religion)
                                </dd>

                                <dt class="col-md-3">
                                    @Html.DisplayNameFor(model => model.MotherName)
                                </dt>
                                <dd class="col-md-9">
                                    @Html.DisplayFor(model => model.MotherName)
                                </dd>
                            </dl>
                        </div>

                    </div>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-end">

                        <a class="btn btn-outline-danger btn-sm mr-2" asp-controller="JobSeekerDashboard" asp-action="Index">
                            <i class="far fa-window-close"></i> Cancel
                        </a>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

Tactsoft/Views/PersonalDetails/Index.cshtml
@model IEnumerable<Tactsoft.Core.Entities.PersonalDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h4 class="m-0">@ViewData["Title"]</h4>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Dashboard">Dashboard</a></li>
                        <li class="breadcrumb-item active">@ViewData["Title"]</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <h3 class="card-title">@ViewData["Title"] List</h3>
                        <a class="btn btn-outline-primary btn-sm" asp-action="Create">
                            <i class="fa-regular fa-pen-to-square"></i> Add New
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.FirstName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.LastName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.FatherName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.MotherName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DateofBirth)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Gender)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Religion)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.MaritalStatus)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Nationality)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.NationalId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PassportNumber)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PassportIssueDate)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PrimaryMobile)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.SecondaryMobile)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.EmergencContact)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PrimaryEmail)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.AlternateEmail)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.BloodGroupId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Height)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Weight)
                                </th>


                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FatherName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LastName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FatherName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MotherName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DateofBirth)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Gender)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Religion)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MaritalStatus)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nationality)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NationalId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PassportNumber)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PassportIssueDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PrimaryMobile)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SecondaryMobile)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EmergencContact)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PrimaryEmail)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.AlternateEmail)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.BloodGroup.BloodGroupName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Height)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Weight)
                                    </td>

                                    <td>
                                        @Html.ActionLink("", "Edit", new { id = item.Id }, new { @class = "fa-regular fa-pen-to-square", @style = "color:green" }) |
                                        @Html.ActionLink("", "Details", new { id = item.Id }, new { @class = "fa-regular fa-eye", @style = "color:blue" }) |
                                        @Html.ActionLink("", "Delete", new { id = item.Id }, new { @class = "fa-regular fa-trash-can", @style = "color: red" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</div>
<partial name="~/Views/UIComponents/_bootstrapAlert.cshtml" />

@section Scripts{
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": true, "autoWidth": true,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        });
    </script>
}